CREATE TABLE prayer_times (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    fajr_start TIME NOT NULL,
    fajr_end TIME NOT NULL,
    sunrise TIME NOT NULL,
    dhuhr_start TIME NOT NULL,
    dhuhr_end TIME NOT NULL,
    asr_start TIME NOT NULL,
    asr_end TIME NOT NULL,
    maghrib_start TIME NOT NULL,
    maghrib_end TIME NOT NULL,
    isha_start TIME NOT NULL,
    isha_end TIME NOT NULL
);

CREATE INDEX idx_prayer_times_date ON prayer_times(date);
